### ISSUE TITLE
Logstash support

### ISSUE THREAD

**Issue by cballesta** [neo9/n9-node-log#2]
Could you support Logstash transport ?
https://github.com/jaakkos/winston-logstash

**Comment by Atinux** [comment]
`winston-logstash` is out of date and unmaintained

I tried with https://github.com/vanthome/winston-elasticsearch and it works nice, so I added a `transports` property into the options to be able to give custom winston transporters, see [v2.4.0](https://github.com/neo9/n9-node-log/releases/tag/v2.4.0).
